[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[profile.backtesting]
src = "src"
out = "out"
libs = ["lib"]
# Enable FFI for backtesting (required for external script execution)
ffi = true
# Increase gas limit for backtesting operations
gas_limit = 100000000
# Include test directory
test = "test"

[doc]
title = "Credible Standard Library"
repository = "https://github.com/phylaxsystems/credible-std"
ignore = ["test/**", "lib/**"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
