name: Solidity Test CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  solidity-base:
    uses: phylaxsystems/actions/.github/workflows/solidity-base.yaml@main
    with:
      gas-diff-tolerance: 25
      forge-test-args: "--no-match-path 'test/backtesting/**'"
      disable-gas-snapshot: true
